#!/usr/bin/python
# clean up GPIO pins after latest disaster

import argparse
import RPi.GPIO as GPIO

# *ALL* i/o pins on Pi 2
PINS_ALL = (3,5,7,8,10,11,12,13,15,16,18,19,
     21,22,23,24,26,29,
     31,32,33,35,36,37,38,40)

# pure GPIO pins with no extra function
PINS_SOME = (7,11,12,13,15,16,18)


# parse command line args

def handle_args():
   parser = argparse.ArgumentParser()
   parser.add_argument('-a', '--all',
		       help='clear ALL I/O pings',
		       action = 'store_true')
   args = parser.parse_args()
   return args


# main
if __name__ == '__main__':
   args = handle_args()

   PINS = PINS_ALL if args.all else PINS_SOME
   GPIO.setmode(GPIO.BOARD)
   GPIO.setwarnings(False)
   # set all pins as output low
   print('clearing ',PINS)
   GPIO.setup( PINS, GPIO.OUT, initial=GPIO.LOW)
   GPIO.cleanup()
